# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preferencje.ui'
#
# Created: Sat Apr 21 14:40:26 2012
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(363, 365)
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Preferencje", None, QtGui.QApplication.UnicodeUTF8))
        Dialog.setSizeGripEnabled(True)
        Dialog.setModal(True)
        self.twOpcje = QtGui.QTabWidget(Dialog)
        self.twOpcje.setGeometry(QtCore.QRect(6, 12, 351, 311))
        self.twOpcje.setTabShape(QtGui.QTabWidget.Rounded)
        self.twOpcje.setObjectName(_fromUtf8("twOpcje"))
        self.tabOgolne = QtGui.QWidget()
        self.tabOgolne.setObjectName(_fromUtf8("tabOgolne"))
        self.leNick = QtGui.QLineEdit(self.tabOgolne)
        self.leNick.setGeometry(QtCore.QRect(151, 13, 161, 23))
        self.leNick.setObjectName(_fromUtf8("leNick"))
        self.lbNick = QtGui.QLabel(self.tabOgolne)
        self.lbNick.setGeometry(QtCore.QRect(17, 16, 131, 17))
        self.lbNick.setText(QtGui.QApplication.translate("Dialog", "Nazwa użytkownika:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbNick.setObjectName(_fromUtf8("lbNick"))
        self.lbStatus = QtGui.QLabel(self.tabOgolne)
        self.lbStatus.setGeometry(QtCore.QRect(17, 55, 131, 20))
        self.lbStatus.setText(QtGui.QApplication.translate("Dialog", "Początkowy status:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbStatus.setObjectName(_fromUtf8("lbStatus"))
        self.chbEnterSend = QtGui.QCheckBox(self.tabOgolne)
        self.chbEnterSend.setGeometry(QtCore.QRect(16, 82, 321, 22))
        self.chbEnterSend.setText(QtGui.QApplication.translate("Dialog", "Wysyła wiadomość za pomocą klawisza ENTER", None, QtGui.QApplication.UnicodeUTF8))
        self.chbEnterSend.setChecked(False)
        self.chbEnterSend.setObjectName(_fromUtf8("chbEnterSend"))
        self.cbStatus = QtGui.QComboBox(self.tabOgolne)
        self.cbStatus.setGeometry(QtCore.QRect(152, 52, 161, 23))
        self.cbStatus.setObjectName(_fromUtf8("cbStatus"))
        self.cbStatus.addItem(_fromUtf8(""))
        self.cbStatus.setItemText(0, QtGui.QApplication.translate("Dialog", "Dostępny", None, QtGui.QApplication.UnicodeUTF8))
        self.cbStatus.addItem(_fromUtf8(""))
        self.cbStatus.setItemText(1, QtGui.QApplication.translate("Dialog", "Zaraz wracam", None, QtGui.QApplication.UnicodeUTF8))
        self.cbStatus.addItem(_fromUtf8(""))
        self.cbStatus.setItemText(2, QtGui.QApplication.translate("Dialog", "Zajęty", None, QtGui.QApplication.UnicodeUTF8))
        self.cbStatus.addItem(_fromUtf8(""))
        self.cbStatus.setItemText(3, QtGui.QApplication.translate("Dialog", "Niedostępny", None, QtGui.QApplication.UnicodeUTF8))
        self.twOpcje.addTab(self.tabOgolne, _fromUtf8(""))
        self.tabHistoria = QtGui.QWidget()
        self.tabHistoria.setObjectName(_fromUtf8("tabHistoria"))
        self.chbZapiszRozmowe = QtGui.QCheckBox(self.tabHistoria)
        self.chbZapiszRozmowe.setGeometry(QtCore.QRect(10, 20, 221, 22))
        self.chbZapiszRozmowe.setText(QtGui.QApplication.translate("Dialog", "Zapisz rozmowę do dziennika", None, QtGui.QApplication.UnicodeUTF8))
        self.chbZapiszRozmowe.setObjectName(_fromUtf8("chbZapiszRozmowe"))
        self.chbZapiszPowiadomienia = QtGui.QCheckBox(self.tabHistoria)
        self.chbZapiszPowiadomienia.setGeometry(QtCore.QRect(10, 44, 231, 22))
        self.chbZapiszPowiadomienia.setText(QtGui.QApplication.translate("Dialog", "Zapisz komunikaty programu", None, QtGui.QApplication.UnicodeUTF8))
        self.chbZapiszPowiadomienia.setObjectName(_fromUtf8("chbZapiszPowiadomienia"))
        self.lbKatalogHistorii = QtGui.QLabel(self.tabHistoria)
        self.lbKatalogHistorii.setGeometry(QtCore.QRect(10, 89, 101, 17))
        self.lbKatalogHistorii.setText(QtGui.QApplication.translate("Dialog", "Katalog historii:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbKatalogHistorii.setObjectName(_fromUtf8("lbKatalogHistorii"))
        self.lbNazwaPliku = QtGui.QLabel(self.tabHistoria)
        self.lbNazwaPliku.setGeometry(QtCore.QRect(10, 130, 91, 17))
        self.lbNazwaPliku.setText(QtGui.QApplication.translate("Dialog", "Nazwa pliku:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbNazwaPliku.setObjectName(_fromUtf8("lbNazwaPliku"))
        self.leNazwaPliku = QtGui.QLineEdit(self.tabHistoria)
        self.leNazwaPliku.setGeometry(QtCore.QRect(119, 128, 221, 23))
        self.leNazwaPliku.setObjectName(_fromUtf8("leNazwaPliku"))
        self.leKatalogHistorii = QtGui.QLineEdit(self.tabHistoria)
        self.leKatalogHistorii.setGeometry(QtCore.QRect(117, 86, 201, 23))
        self.leKatalogHistorii.setObjectName(_fromUtf8("leKatalogHistorii"))
        self.pbKatalogHistorii = QtGui.QPushButton(self.tabHistoria)
        self.pbKatalogHistorii.setGeometry(QtCore.QRect(320, 83, 21, 27))
        self.pbKatalogHistorii.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.pbKatalogHistorii.setObjectName(_fromUtf8("pbKatalogHistorii"))
        self.gbZmienne = QtGui.QGroupBox(self.tabHistoria)
        self.gbZmienne.setGeometry(QtCore.QRect(8, 150, 331, 131))
        self.gbZmienne.setTitle(QtGui.QApplication.translate("Dialog", "Zmienne używane w nazwie pliku", None, QtGui.QApplication.UnicodeUTF8))
        self.gbZmienne.setObjectName(_fromUtf8("gbZmienne"))
        self.lbZmienne = QtGui.QLabel(self.gbZmienne)
        self.lbZmienne.setGeometry(QtCore.QRect(10, 20, 311, 111))
        self.lbZmienne.setText(QtGui.QApplication.translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">%d - Dzień miesiąca</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">%D - Tekstowy opis angielskiej nazwy dnia</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">%m - Liczbowa forma miesiąca</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">%M - Krótki, angielski opis miesiąca</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">%A - Pora dnia - AM lub PM</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">%h - Godzina, w formacie 12-godzinnym</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">%H - Godzina, w formacie 24-godzinnym</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">%i - Minuty</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lbZmienne.setObjectName(_fromUtf8("lbZmienne"))
        self.twOpcje.addTab(self.tabHistoria, _fromUtf8(""))
        self.tabDzwiek = QtGui.QWidget()
        self.tabDzwiek.setObjectName(_fromUtf8("tabDzwiek"))
        self.chbGlosnik = QtGui.QCheckBox(self.tabDzwiek)
        self.chbGlosnik.setGeometry(QtCore.QRect(10, 20, 321, 22))
        self.chbGlosnik.setText(QtGui.QApplication.translate("Dialog", "Włącz powiadamianie głośnikiem systemowym", None, QtGui.QApplication.UnicodeUTF8))
        self.chbGlosnik.setObjectName(_fromUtf8("chbGlosnik"))
        self.chbDzwiek = QtGui.QCheckBox(self.tabDzwiek)
        self.chbDzwiek.setGeometry(QtCore.QRect(10, 40, 231, 22))
        self.chbDzwiek.setText(QtGui.QApplication.translate("Dialog", "Włącz powiadamianie dźwiękami", None, QtGui.QApplication.UnicodeUTF8))
        self.chbDzwiek.setObjectName(_fromUtf8("chbDzwiek"))
        self.leDzwiekDolaczenia = QtGui.QLineEdit(self.tabDzwiek)
        self.leDzwiekDolaczenia.setGeometry(QtCore.QRect(10, 150, 249, 23))
        self.leDzwiekDolaczenia.setObjectName(_fromUtf8("leDzwiekDolaczenia"))
        self.leDzwiekPrzychodzacej = QtGui.QLineEdit(self.tabDzwiek)
        self.leDzwiekPrzychodzacej.setGeometry(QtCore.QRect(10, 90, 251, 23))
        self.leDzwiekPrzychodzacej.setObjectName(_fromUtf8("leDzwiekPrzychodzacej"))
        self.lbDzwiekPrzychodzacej = QtGui.QLabel(self.tabDzwiek)
        self.lbDzwiekPrzychodzacej.setGeometry(QtCore.QRect(10, 70, 231, 17))
        self.lbDzwiekPrzychodzacej.setText(QtGui.QApplication.translate("Dialog", "Dźwięk wiadomości przychodzącej:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbDzwiekPrzychodzacej.setObjectName(_fromUtf8("lbDzwiekPrzychodzacej"))
        self.lbDzwiekDolaczenia = QtGui.QLabel(self.tabDzwiek)
        self.lbDzwiekDolaczenia.setGeometry(QtCore.QRect(10, 130, 231, 17))
        self.lbDzwiekDolaczenia.setText(QtGui.QApplication.translate("Dialog", "Dźwięk dodłączenia użytkownika:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbDzwiekDolaczenia.setObjectName(_fromUtf8("lbDzwiekDolaczenia"))
        self.pbDzwiekDolaczenia = QtGui.QPushButton(self.tabDzwiek)
        self.pbDzwiekDolaczenia.setGeometry(QtCore.QRect(264, 147, 20, 27))
        self.pbDzwiekDolaczenia.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.pbDzwiekDolaczenia.setObjectName(_fromUtf8("pbDzwiekDolaczenia"))
        self.pbDzwiekPrzychodzacej = QtGui.QPushButton(self.tabDzwiek)
        self.pbDzwiekPrzychodzacej.setGeometry(QtCore.QRect(266, 88, 21, 27))
        self.pbDzwiekPrzychodzacej.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.pbDzwiekPrzychodzacej.setObjectName(_fromUtf8("pbDzwiekPrzychodzacej"))
        self.twOpcje.addTab(self.tabDzwiek, _fromUtf8(""))
        self.tabKolory = QtGui.QWidget()
        self.tabKolory.setObjectName(_fromUtf8("tabKolory"))
        self.frmKolorPrzychodzacej = QtGui.QFrame(self.tabKolory)
        self.frmKolorPrzychodzacej.setGeometry(QtCore.QRect(193, 10, 41, 41))
        self.frmKolorPrzychodzacej.setFrameShape(QtGui.QFrame.Box)
        self.frmKolorPrzychodzacej.setFrameShadow(QtGui.QFrame.Raised)
        self.frmKolorPrzychodzacej.setObjectName(_fromUtf8("frmKolorPrzychodzacej"))
        self.frmKolorWyslanej = QtGui.QFrame(self.tabKolory)
        self.frmKolorWyslanej.setGeometry(QtCore.QRect(193, 60, 41, 41))
        self.frmKolorWyslanej.setFrameShape(QtGui.QFrame.Box)
        self.frmKolorWyslanej.setFrameShadow(QtGui.QFrame.Raised)
        self.frmKolorWyslanej.setObjectName(_fromUtf8("frmKolorWyslanej"))
        self.frmKolorKomunikatu = QtGui.QFrame(self.tabKolory)
        self.frmKolorKomunikatu.setGeometry(QtCore.QRect(193, 110, 41, 41))
        self.frmKolorKomunikatu.setFrameShape(QtGui.QFrame.Box)
        self.frmKolorKomunikatu.setFrameShadow(QtGui.QFrame.Raised)
        self.frmKolorKomunikatu.setObjectName(_fromUtf8("frmKolorKomunikatu"))
        self.lbKolorPrzychodzacej = QtGui.QLabel(self.tabKolory)
        self.lbKolorPrzychodzacej.setGeometry(QtCore.QRect(7, 22, 181, 17))
        self.lbKolorPrzychodzacej.setText(QtGui.QApplication.translate("Dialog", "Wiadomość przychodząca:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbKolorPrzychodzacej.setObjectName(_fromUtf8("lbKolorPrzychodzacej"))
        self.lbKolorWyslanej = QtGui.QLabel(self.tabKolory)
        self.lbKolorWyslanej.setGeometry(QtCore.QRect(10, 71, 171, 17))
        self.lbKolorWyslanej.setText(QtGui.QApplication.translate("Dialog", "Wiadomość wysłana:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbKolorWyslanej.setObjectName(_fromUtf8("lbKolorWyslanej"))
        self.lbKolorKomunikatu = QtGui.QLabel(self.tabKolory)
        self.lbKolorKomunikatu.setGeometry(QtCore.QRect(11, 124, 171, 17))
        self.lbKolorKomunikatu.setText(QtGui.QApplication.translate("Dialog", "Komunikaty programu:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbKolorKomunikatu.setObjectName(_fromUtf8("lbKolorKomunikatu"))
        self.pbKolorPrzychodzacej = QtGui.QPushButton(self.tabKolory)
        self.pbKolorPrzychodzacej.setGeometry(QtCore.QRect(252, 17, 84, 27))
        self.pbKolorPrzychodzacej.setText(QtGui.QApplication.translate("Dialog", "Zmień", None, QtGui.QApplication.UnicodeUTF8))
        self.pbKolorPrzychodzacej.setObjectName(_fromUtf8("pbKolorPrzychodzacej"))
        self.pbKolorWyslanej = QtGui.QPushButton(self.tabKolory)
        self.pbKolorWyslanej.setGeometry(QtCore.QRect(253, 65, 84, 27))
        self.pbKolorWyslanej.setText(QtGui.QApplication.translate("Dialog", "Zmień", None, QtGui.QApplication.UnicodeUTF8))
        self.pbKolorWyslanej.setObjectName(_fromUtf8("pbKolorWyslanej"))
        self.pbKolorKomunikatu = QtGui.QPushButton(self.tabKolory)
        self.pbKolorKomunikatu.setGeometry(QtCore.QRect(254, 117, 84, 27))
        self.pbKolorKomunikatu.setText(QtGui.QApplication.translate("Dialog", "Zmień", None, QtGui.QApplication.UnicodeUTF8))
        self.pbKolorKomunikatu.setObjectName(_fromUtf8("pbKolorKomunikatu"))
        self.twOpcje.addTab(self.tabKolory, _fromUtf8(""))
        self.pbAnuluj = QtGui.QPushButton(Dialog)
        self.pbAnuluj.setGeometry(QtCore.QRect(276, 332, 80, 27))
        self.pbAnuluj.setText(QtGui.QApplication.translate("Dialog", "Anuluj", None, QtGui.QApplication.UnicodeUTF8))
        self.pbAnuluj.setObjectName(_fromUtf8("pbAnuluj"))
        self.pbOK = QtGui.QPushButton(Dialog)
        self.pbOK.setGeometry(QtCore.QRect(176, 332, 80, 27))
        self.pbOK.setText(QtGui.QApplication.translate("Dialog", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.pbOK.setObjectName(_fromUtf8("pbOK"))
        self.lbNick.setBuddy(self.leNick)
        self.lbStatus.setBuddy(self.cbStatus)
        self.lbKatalogHistorii.setBuddy(self.leKatalogHistorii)
        self.lbNazwaPliku.setBuddy(self.leNazwaPliku)
        self.lbDzwiekPrzychodzacej.setBuddy(self.leDzwiekPrzychodzacej)
        self.lbDzwiekDolaczenia.setBuddy(self.leDzwiekDolaczenia)

        self.retranslateUi(Dialog)
        self.twOpcje.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        self.twOpcje.setTabText(self.twOpcje.indexOf(self.tabOgolne), QtGui.QApplication.translate("Dialog", "Ogólne", None, QtGui.QApplication.UnicodeUTF8))
        self.twOpcje.setTabText(self.twOpcje.indexOf(self.tabHistoria), QtGui.QApplication.translate("Dialog", "Historia", None, QtGui.QApplication.UnicodeUTF8))
        self.twOpcje.setTabText(self.twOpcje.indexOf(self.tabDzwiek), QtGui.QApplication.translate("Dialog", "Dźwięk", None, QtGui.QApplication.UnicodeUTF8))
        self.twOpcje.setTabText(self.twOpcje.indexOf(self.tabKolory), QtGui.QApplication.translate("Dialog", "Kolory", None, QtGui.QApplication.UnicodeUTF8))

